In [308]:
import camelot

In [309]:
def pdf_tables():
    tables = camelot.read_pdf("boletim_covid_07_7_21pdf.pdf", pages="2-4", split_text=True, process_background=True)
    return tables

In [310]:
tables = pdf_tables()
print(tables)

#20210520_TO.pdf
#20210630_TO.pdf

camelot.core.pd.set_option('display.max_rows', None)
camelot.core.pd.set_option('display.max_columns', None)
camelot.core.pd.set_option('display.width', None)
camelot.core.pd.set_option('display.max_colwidth', None)

for table in tables:
    table.df.replace(to_replace='[0-9]+[ ]{0,}\\n', value='', inplace=True, regex=True)
    display(table.df)

<TableList n=9>

              0    1
0    0 a 9 anos   47
1  10 a 19 anos   81
2  20 a 39 anos  354
3  40 a 59 anos  269
4  60 a 69 anos   61
5         70 e+   45
6         TOTAL  857

                           0       1
0                  MUNICÍPIO   TOTAL
1                     PALMAS  40.859
2                  ARAGUAÍNA  29.128
3                     GURUPI  10.306
4             PORTO NACIONAL   7.976
5       PARAÍSO DO TOCANTINS   7.193
6       COLINAS DO TOCANTINS   6.640
7                     GUARAÍ   2.733
8        FORMOSO DO ARAGUAIA   2.499
9                  MIRANORTE   2.172
10                ARAGUATINS   2.042
11                   XAMBIOÁ   2.021
12            TOCANTINÓPOLIS   1.960
13     MIRACEMA DO TOCANTINS   1.765
14         LAGOA DA CONFUSÃO   1.531
15                    ANANÁS   1.463
16              PEDRO AFONSO   1.441
17            AUGUSTINÓPOLIS   1.371
18                DIANÓPOLIS   1.243
19                  ALVORADA   1.034
20                NATIVIDADE   1.011
21        AXIXÁ DO TOCANTINS   1.005
22             PALMEIRÓPOLIS     963
23               NOVA OLINDA     887
24              SILVANÓPOLIS     884
25                  GOIATINS     850
26       BURITI DO TOCANTINS     802
27                  ARAGUAÇU     785
28    SÃO BENTO DO TOCANTINS     783
29                     PEIXE     779
30                   ITACAJÁ     766
31              WANDERLÂNDIA     763
32   PONTE ALTA DO TOCANTINS     756
33  DIVINÓPOLIS DO TOCANTINS     721
34                   COLMÉIA     720
35               BARROLÂNDIA     705
36       CARIRI DO TOCANTINS     695
37                TAGUATINGA     677
38      SANTA FÉ DO ARAGUAIA     652

                             0      1
0                    MUNICÍPIO  TOTAL
1                 BABAÇULÂNDIA    610
2                FIGUEIRÓPOLIS    600
3      SÍTIO NOVO DO TOCANTINS    599
4      SÃO MIGUEL DO TOCANTINS    576
5                  ESPERANTINA    575
6         ALIANÇA DO TOCANTINS    556
7                AGUIARNÓPOLIS    549
8                    COMBINADO    541
9                       FÁTIMA    536
10                     SAMPAIO    525
11      PALMEIRAS DO TOCANTINS    524
12                     ARRAIAS    523
13                DARCINÓPOLIS    511
14                  ARAGUACEMA    498
15  SÃO SEBASTIÃO DO TOCANTINS    484
16             CARRASCO BONITO    483
17                  ITAGUATINS    482
18                  ARAGOMINAS    473
19                     CASEARA    465
20                  PEQUIZEIRO    465
21                     TABOCÃO    463
22                 PALMEIRANTE    461
23                      NAZARÉ    457
24              BERNARDO SAYÃO    452
25              MONTE DO CARMO    445
26                MURICILÂNDIA    445
27                    ARAGUANÃ    422
28          BREJINHO DE NAZARÉ    418
29                    ARAPOEMA    412
30   BANDEIRANTES DO TOCANTINS    402
31                  FILADÉLFIA    399
32                      PARANÃ    375
33             COUTO MAGALHÃES    365
34        ITAPORÃ DO TOCANTINS    362
35             NOVA ROSALÂNDIA    357
36                  PAU D'ARCO    348
37                 SÃO VALÉRIO    341
38                 ITAPIRATINS    332
39   MARIANÓPOLIS DO TOCANTINS    327
40               CAMPOS LINDOS    323

                               0        1
0                      MUNICÍPIO    TOTAL
1          CHAPADA DA NATIVIDADE      183
2       MAURILÂNDIA DO TOCANTINS      182
3                       SUCUPIRA      176
4            AURORA DO TOCANTINS      172
5       BRASILÂNDIA DO TOCANTINS      170
6                        PIRAQUÊ      167
7               CHAPADA DE AREIA      164
8      SÃO SALVADOR DO TOCANTINS      152
9   SANTA TEREZINHA DO TOCANTINS      150
10                      MATEIROS      146
11                      TUPIRAMA      143
12                       LAJEADO      139
13        SÃO FÉLIX DO TOCANTINS      139
14           TAIPAS DO TOCANTINS      134
15      MONTE SANTO DO TOCANTINS      133
16                       LIZARDA      129
17        BOM JESUS DO TOCANTINS      124
18        CONCEIÇÃO DO TOCANTINS      120
19                      IPUEIRAS      120
20                 BARRA DO OURO      119
21                  CACHOEIRINHA      117
22              RIO DA CONCEIÇÃO      114
23            OLIVEIRA DE FÁTIMA      113
24           CRIXÁS DO TOCANTINS      111
25     PORTO ALEGRE DO TOCANTINS       95
26                    LAVANDEIRA       93
27                       JUARINA       88
28                    TUPIRATINS       80
29                   NOVO ALEGRE       63
30                         TOTAL  171.614

                            0      1
0                   MUNICÍPIO  TOTAL
1      APARECIDA DO RIO NEGRO    313
2     PONTE ALTA DO BOM JESUS    313
3                RIO DOS BOIS    310
4                       DUERÉ    298
5          PRESIDENTE KENNEDY    296
6     SANTA ROSA DO TOCANTINS    290
7                 SANDOLÂNDIA    287
8                 PRAIA NORTE    276
9                   RIACHINHO    275
10    SANTA RITA DO TOCANTINS    270
11               CRISTALÂNDIA    268
12                  GOIANORTE    267
13                       PIUM    266
14                ABREULÂNDIA    262
15                   RIO SONO    262
16   SANTA MARIA DO TOCANTINS    260
17     PINDORAMA DO TOCANTINS    255
18                    TALISMÃ    227
19  SANTA TEREZA DO TOCANTINS    222
20                     PUGMIL    220
21              RECURSOLÂNDIA    218
22                CARMOLÂNDIA    215
23         LAGOA DO TOCANTINS    213
24                     ANGICO    211
25                      ALMAS    198
26           JAÚ DO TOCANTINS    197
27                NOVO JARDIM    197
28                 CENTENÁRIO    191
29                LUZINÓPOLIS    191
30                NOVO ACORDO    187

                             0      1
0                    MUNICÍPIO  TOTAL
1     DIVINÓPOLIS DO TOCANTINS      8
2                       FÁTIMA      8
3             JAÚ DO TOCANTINS      8
4    MARIANÓPOLIS DO TOCANTINS      8
5              NOVA ROSALÂNDIA      8
6      PONTE ALTA DO TOCANTINS      8
7       SÃO BENTO DO TOCANTINS      8
8                  SÃO VALÉRIO      8
9      SÍTIO NOVO DO TOCANTINS      8
10                DARCINÓPOLIS      7
11                     TABOCÃO      7
12              MONTE DO CARMO      7
13                      NAZARÉ      7
14                 PALMEIRANTE      7
15                  PAU D'ARCO      7
16                 PRAIA NORTE      7
17                 ABREULÂNDIA      6
18                    ARAPOEMA      6
19   BANDEIRANTES DO TOCANTINS      6
20               BARRA DO OURO      6
21              BERNARDO SAYÃO      6
22                  CENTENÁRIO      6
23             COUTO MAGALHÃES      6
24                   GOIANORTE      6
25          LAGOA DO TOCANTINS      6
26    MONTE SANTO DO TOCANTINS      6
27     PONTE ALTA DO BOM JESUS      6
28                 SANDOLÂNDIA      6
29      APARECIDA DO RIO NEGRO      5
30                BABAÇULÂNDIA      5
31                  FILADÉLFIA      5
32      PALMEIRAS DO TOCANTINS      5
33                      PARANÃ      5
34          PRESIDENTE KENNEDY      5
35     SANTA ROSA DO TOCANTINS      5
36                       ALMAS      4
37                     ARRAIAS      4
38    BRASILÂNDIA DO TOCANTINS      4
39                 CARMOLÂNDIA      4
40                    IPUEIRAS      4
41                        PIUM      4
42               RECURSOLÂNDIA      4
43                   RIACHINHO      4
44                RIO DOS BOIS      4
45                     SAMPAIO      4
46   SANTA TEREZA DO TOCANTINS      4
47  SÃO SEBASTIÃO DO TOCANTINS      4
48                      ANGICO      3
49         AURORA DO TOCANTINS      3
50      BOM JESUS DO TOCANTINS      3
51               CAMPOS LINDOS      3
52             CARRASCO BONITO      3
53            CHAPADA DE AREIA      3

                           0      1
0                  MUNICÍPIO  TOTAL
1                     PALMAS    507
2                  ARAGUAÍNA    384
3                     GURUPI    174
4             PORTO NACIONAL    162
5       PARAÍSO DO TOCANTINS    161
6       COLINAS DO TOCANTINS    102
7                     GUARAÍ     63
8                  MIRANORTE     52
9                 ARAGUATINS     50
10       FORMOSO DO ARAGUAIA     43
11     MIRACEMA DO TOCANTINS     42
12            TOCANTINÓPOLIS     41
13               NOVA OLINDA     36
14                   XAMBIOÁ     27
15            AUGUSTINÓPOLIS     26
16                DIANÓPOLIS     26
17                   COLMÉIA     24
18              SILVANÓPOLIS     23
19                    ANANÁS     22
20              PEDRO AFONSO     22
21         LAGOA DA CONFUSÃO     21
22             PALMEIRÓPOLIS     21
23      ALIANÇA DO TOCANTINS     20
24               BARROLÂNDIA     20
25                  ALVORADA     18
26                  ARAGUAÇU     18
27        AXIXÁ DO TOCANTINS     16
28  DOIS IRMÃOS DO TOCANTINS     16
29                NATIVIDADE     16
30                     PEIXE     16
31               ESPERANTINA     15
32   SÃO MIGUEL DO TOCANTINS     14
33                TAGUATINGA     14
34             FIGUEIRÓPOLIS     13
35             AGUIARNÓPOLIS     12
36                  ARAGUANÃ     12
37       CARIRI DO TOCANTINS     12
38                   CASEARA     12
39                ITAGUATINS     12
40                ARAGUACEMA     11
41        BREJINHO DE NAZARÉ     11
42      SANTA FÉ DO ARAGUAIA     11
43              WANDERLÂNDIA     11
44                TOCANTÍNIA     10
45                ARAGOMINAS      9
46                 COMBINADO      9
47              CRISTALÂNDIA      9
48                     DUERÉ      9
49                  GOIATINS      9
50                   ITACAJÁ      9
51                PEQUIZEIRO      9
52       BURITI DO TOCANTINS      8
53    CONCEIÇÃO DO TOCANTINS      8

                               0      1
0                      MUNICÍPIO  TOTAL
1                    ITAPIRATINS      3
2           ITAPORÃ DO TOCANTINS      3
3                        LAJEADO      3
4                        LIZARDA      3
5       MAURILÂNDIA DO TOCANTINS      3
6                    NOVO ACORDO      3
7   SANTA TEREZINHA DO TOCANTINS      3
8                   CACHOEIRINHA      2
9                        JUARINA      2
10                   LUZINÓPOLIS      2
11                  MURICILÂNDIA      2
12                   NOVO ALEGRE      2
13     PORTO ALEGRE DO TOCANTINS      2
14              RIO DA CONCEIÇÃO      2

                            0      1
0                   MUNICÍPIO  TOTAL
1                    RIO SONO      2
2    SANTA MARIA DO TOCANTINS      2
3   SÃO SALVADOR DO TOCANTINS      2
4                     TALISMÃ      2
5                    TUPIRAMA      2
6       CHAPADA DA NATIVIDADE      1
7                 NOVO JARDIM      1
8          OLIVEIRA DE FÁTIMA      1
9      PINDORAMA DO TOCANTINS      1
10                    PIRAQUÊ      1
11                     PUGMIL      1
12    SANTA RITA DO TOCANTINS      1
13     SÃO FÉLIX DO TOCANTINS      1
14                 TUPIRATINS      1
15                      TOTAL  2.766